default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tukuro
  password: rukia2323

development:
  <<: *default
  database: anizkuro_development

test:
  <<: *default
  database: anizkuro_test

production:
  <<: *default
  database: anizkuro_production
  username: anizkuro
  password: <%= ENV['ANIZKURO_DATABASE_PASSWORD'] %>
